# ------------------------------------------------------------------------
#  Publish Docker image from the stable snapshot into Github repository
# ------------------------------------------------------------------------

name: publish-stable

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-publish-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          add_git_labels: true
          tags: latest,${{ env.TAG }}

          registry: docker.pkg.github.com
          repository: ${{ github.REPOSITORY }}/cloud-game

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'PLACEHOLDER'

      - name: Redeploy all instances
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
        run: ./.github/workflows/redeploy/redeploy.sh

